version: "3.8"

name: sdp-project

services:
  # SDP SERVER
  server:
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ../app:/app
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 0
    depends_on:
      - redis

  # REDIS
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
